baseURL = 'https://joseflekardal.github.io/'
languageCode = 'en-us'
title = 'josef lekardal'
enableEmoji = true
enableGitInfo = true
googleAnalytics = 'G-YGFJ1SMNEM'

[markup]
  [markup.highlight]
    style = 'github-dark'


